version: "3"
services:

  php-hello-world:
    image: lmeadows/php-hello-world:demo
    ports:
      - 4000:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
